import { Brain, Target, Route, ShieldCheck, Lightbulb, FileText, Gauge } from 'lucide-react'
import type { AIInsight } from '../lib/ai-insight'

interface AIInsightPanelProps {
  insight: AIInsight
  riskLevel: 'safe' | 'caution' | 'suspicious' | 'dangerous'
}

export default function AIInsightPanel({ insight, riskLevel }: AIInsightPanelProps) {
  const isThreat = riskLevel === 'dangerous' || riskLevel === 'suspicious'

  return (
    <div className="glass rounded-2xl p-6 sm:p-8 space-y-6 border border-primary-500/10">
      {/* Header */}
      <div className="flex items-center gap-2">
        <div className="w-8 h-8 rounded-lg bg-primary-500/15 flex items-center justify-center">
          <Brain className="w-5 h-5 text-primary-400" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-slate-200">AI Security Analyst Report</h3>
          <p className="text-xs text-slate-500">Generated by PhishGuard's analysis engine</p>
        </div>
      </div>

      {/* Headline / Classification */}
      <div className={`p-4 rounded-xl border ${
        riskLevel === 'dangerous' ? 'bg-error-500/10 border-error-500/20' :
        riskLevel === 'suspicious' ? 'bg-accent-500/10 border-accent-500/20' :
        riskLevel === 'caution' ? 'bg-warning-500/10 border-warning-500/20' :
        'bg-success-500/10 border-success-500/20'
      }`}>
        <div className="flex items-center gap-2 mb-1">
          <span className={`text-xs uppercase tracking-wider font-semibold ${
            riskLevel === 'dangerous' ? 'text-error-400' :
            riskLevel === 'suspicious' ? 'text-accent-400' :
            riskLevel === 'caution' ? 'text-warning-400' : 'text-success-400'
          }`}>
            {riskLevel === 'dangerous' ? 'Threat Confirmed' :
             riskLevel === 'suspicious' ? 'Likely Threat' :
             riskLevel === 'caution' ? 'Needs Review' : 'No Threat'}
          </span>
          <span className="text-xs text-slate-500">·</span>
          <span className="text-xs text-slate-500">{insight.classification}</span>
        </div>
        <h4 className="text-base font-semibold text-slate-100">{insight.headline}</h4>
      </div>

      {/* Risk Narrative */}
      <div>
        <h4 className="text-xs uppercase tracking-wider text-slate-500 mb-2 flex items-center gap-1.5">
          <FileText className="w-3.5 h-3.5" />
          Risk Assessment Narrative
        </h4>
        <p className="text-sm text-slate-300 leading-relaxed">{insight.riskNarrative}</p>
      </div>

      {/* Threat Assessment + Target Likelihood */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/50">
          <h4 className="text-xs uppercase tracking-wider text-slate-500 mb-2 flex items-center gap-1.5">
            <Target className="w-3.5 h-3.5" />
            Target Likelihood
          </h4>
          <p className="text-sm text-slate-300 leading-relaxed">{insight.targetLikelihood}</p>
        </div>
        <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/50">
          <h4 className="text-xs uppercase tracking-wider text-slate-500 mb-2 flex items-center gap-1.5">
            <Gauge className="w-3.5 h-3.5" />
            Threat Assessment
          </h4>
          <p className="text-sm text-slate-300 leading-relaxed">{insight.threatAssessment}</p>
        </div>
      </div>

      {/* Attack Vector Analysis */}
      <div>
        <h4 className="text-xs uppercase tracking-wider text-slate-500 mb-2 flex items-center gap-1.5">
          <Route className="w-3.5 h-3.5" />
          Attack Vector Analysis
        </h4>
        <div className="p-4 rounded-xl bg-slate-900/40 border border-slate-800/50">
          <p className="text-sm text-slate-300 leading-relaxed">{insight.attackVector}</p>
        </div>
      </div>

      {/* Recommendations */}
      <div>
        <h4 className="text-xs uppercase tracking-wider text-slate-500 mb-3 flex items-center gap-1.5">
          <Lightbulb className="w-3.5 h-3.5" />
          Security Recommendations
        </h4>
        <div className="space-y-2">
          {insight.recommendations.map((rec, i) => (
            <div
              key={i}
              className={`flex items-start gap-3 p-3 rounded-lg ${
                isThreat
                  ? 'bg-error-500/5 border border-error-500/10'
                  : 'bg-slate-900/40 border border-slate-800/50'
              }`}
            >
              <div className={`shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${
                isThreat ? 'bg-error-500/20 text-error-400' : 'bg-primary-500/20 text-primary-400'
              }`}>
                {i + 1}
              </div>
              <p className="text-sm text-slate-300 leading-relaxed">{rec}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Footer */}
      <div className="flex items-center gap-2 text-xs text-slate-600 pt-2 border-t border-slate-800/50">
        <ShieldCheck className="w-3.5 h-3.5" />
        <span>Generated by PhishGuard AI Analysis Engine · {new Date().toLocaleString()}</span>
      </div>
    </div>
  )
}
